<a href="https://colab.research.google.com/github/cxbxmxcx/PAIGCP/blob/master/PAIGCP_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q tensorflow-text

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_text as text

In [ ]:
ds = tfds.load('imdb_reviews', split='train')
docs = []
for ex in ds.take(10):
  print(ex)
  docs.append(ex)

docs

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">}
{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to

[{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
  'text': <tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">},
 {'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
  'text': <tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually

In [ ]:
tokenizer = tfds.features.text.Tokenizer()

vocabulary_set = set()
for doc in docs:
  some_tokens = tokenizer.tokenize(doc["text"].numpy())
  vocabulary_set.update(some_tokens)

vocab_size = len(vocabulary_set)
vocab_size

817

In [ ]:
docs[1]

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 'text': <tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep because the film was rubbish. The plot development was constant. Constantly slow and boring. Things seemed to happen, but with no explanation of what was causing them or why. I admit, I may have missed part of the film, but i watched the majority of it and everything just seemed to happen of its own accord without any real concern for anything else. I cant recommend this film at all.'>}

In [ ]:
encoder = tfds.features.text.TokenTextEncoder(vocabulary_set)

In [ ]:
encoded = [encoder.encode(doc["text"].numpy()) for doc in docs]
for i in range(len(encoded)):
  print(','.join([str(a) for a in encoded[i]]))

23,115,437,156,88,319,749,217,561,396,458,634,147,410,661,495,249,496,87,731,328,192,152,4,647,561,399,385,757,458,323,712,399,731,740,49,427,288,152,319,271,715,215,23,319,295,437,632,797,714,275,171,804,431,671,680,658,440,89,190,95,772,658,543,399,582,282,175,448,238,710,325,509,422,153,816,248,32,113,410,115,2,192,793,671,187,730,458,793,319,549,115,587,402,255,609,417,497,660,659,549,209,87,296,698,152,338,656,271,698,147,410,271,121,524,497,49,435,741,342,222
497,19,231,484,383,205,424,586,423,192,152,295,459,470,383,793,306,402,357,533,359,535,389,500,422,641,183,190,432,422,556,748,681,793,219,321,183,152,499,497,164,424,479,190,541,115,150,804,405,407,115,43,460,387,422,553,516,182,383,46,192,113,579,343,402,251,115,476,276,661,206,497,270,497,759,19,419,162,402,190,541,192,506,643,190,232,402,222,422,123,748,182,383,46,402,379,663,565,250,255,609,341,282,331,737,497,669,224,152,541,727,763
293,228,190,430,144,590,458,793,666,1,422,378,92,422,713,766,60,84,616,494,189,599,717,

In [ ]:
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(encoded, padding="post")
padded_inputs[0]

array([ 23, 115, 437, 156,  88, 319, 749, 217, 561, 396, 458, 634, 147,
       410, 661, 495, 249, 496,  87, 731, 328, 192, 152,   4, 647, 561,
       399, 385, 757, 458, 323, 712, 399, 731, 740,  49, 427, 288, 152,
       319, 271, 715, 215,  23, 319, 295, 437, 632, 797, 714, 275, 171,
       804, 431, 671, 680, 658, 440,  89, 190,  95, 772, 658, 543, 399,
       582, 282, 175, 448, 238, 710, 325, 509, 422, 153, 816, 248,  32,
       113, 410, 115,   2, 192, 793, 671, 187, 730, 458, 793, 319, 549,
       115, 587, 402, 255, 609, 417, 497, 660, 659, 549, 209,  87, 296,
       698, 152, 338, 656, 271, 698, 147, 410, 271, 121, 524, 497,  49,
       435, 741, 342, 222,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [ ]:
(train_data, test_data), info = tfds.load(
    'imdb_reviews/subwords8k', 
    split = (tfds.Split.TRAIN, tfds.Split.TEST), 
    with_info=True, as_supervised=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteZM42HT/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteZM42HT/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteZM42HT/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0. Subsequent calls will reuse this data.


In [ ]:
encoder = info.features['text'].encoder
encoder.subwords[:20]

['the_',
 ', ',
 '. ',
 'a_',
 'and_',
 'of_',
 'to_',
 's_',
 'is_',
 'br',
 'in_',
 'I_',
 'that_',
 'this_',
 'it_',
 ' /><',
 ' />',
 'was_',
 'The_',
 'as_']

In [ ]:
train_batches = train_data.shuffle(1000).padded_batch(10)
test_batches = test_data.shuffle(1000).padded_batch(10)

In [ ]:
train_batch, train_labels = next(iter(train_batches))
train_batch.numpy()

array([[7963,  693,  519, ...,    0,    0,    0],
       [2540,    2,   15, ...,    0,    0,    0],
       [ 398,   30,  118, ...,    0,    0,    0],
       ...,
       [ 156, 5053,  113, ...,    0,    0,    0],
       [5376, 4265,  344, ...,    0,    0,    0],
       [6553, 1447,  363, ..., 3896, 5444, 7975]])

In [ ]:
import tensorflow.keras as keras
import tensorflow.keras.layers as layers

embedding_dim=16

model = tf.keras.Sequential([
  layers.Embedding(encoder.vocab_size, embedding_dim),
  layers.GlobalAveragePooling1D(),
  layers.Dense(16, activation='relu'),
  layers.Dense(1)
])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          130960    
_________________________________________________________________
global_average_pooling1d (Gl (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 16)                272       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 131,249
Trainable params: 131,249
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(
    train_batches,
    epochs=10,
    validation_data=test_batches, validation_steps=20)

Epoch 1/10
2500/2500 [==============================] - 12s 5ms/step - loss: 0.4926 - accuracy: 0.7108 - val_loss: 0.3306 - val_accuracy: 0.8600
Epoch 2/10
2500/2500 [==============================] - 13s 5ms/step - loss: 0.2789 - accuracy: 0.8854 - val_loss: 0.4401 - val_accuracy: 0.8500
Epoch 3/10
2500/2500 [==============================] - 13s 5ms/step - loss: 0.2241 - accuracy: 0.9118 - val_loss: 0.2924 - val_accuracy: 0.8650
Epoch 4/10
2500/2500 [==============================] - 13s 5ms/step - loss: 0.1918 - accuracy: 0.9276 - val_loss: 0.3970 - val_accuracy: 0.8700
Epoch 5/10
2500/2500 [==============================] - 12s 5ms/step - loss: 0.1713 - accuracy: 0.9352 - val_loss: 0.4221 - val_accuracy: 0.8750
Epoch 6/10
2500/2500 [==============================] - 11s 5ms/step - loss: 0.1515 - accuracy: 0.9446 - val_loss: 0.3310 - val_accuracy: 0.8900
Epoch 7/10
2500/2500 [==============================] - 11s 4ms/step - loss: 0.1403 - accuracy: 0.9484 - val_loss: 0.4280 - val_ac

In [ ]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) 

(8185, 16)


In [ ]:
weights[0]

array([-0.01466625,  0.03343547, -0.01401963, -0.03786296, -0.00279899,
       -0.0047526 ,  0.04494296, -0.0190739 ,  0.0360129 ,  0.00495418,
       -0.020948  ,  0.13313028,  0.15447006, -0.04197033,  0.00154488,
        0.01018907], dtype=float32)

In [ ]:
from scipy.spatial import distance

print(1 - distance.cosine(weights[2850], weights[2900]))
encoder.subwords[2850], encoder.subwords[2900]

-0.8510435819625854


('detail', 'bizarre_')